import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from "@/components/providers/RQProvider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-14 text-3xl">
          <nav className="flex justify-around">
            <div>
              <Link href={"/"}>Home</Link>
            </div>
            <div className="flex gap-16">
              <Link href={"/champions"}>Champions</Link>
              <Link href={"/items"}>Items</Link>
              <Link href={"/rotation"}>Rotation</Link>
            </div>
          </nav>
        </header>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
